// Code generated by MockGen. DO NOT EDIT.
// Source: account.go
//
// Generated by this command:
//
//	mockgen -source=account.go -destination=mocks/account_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nubank/pismo-code-assessment/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockaccountCreator is a mock of accountCreator interface.
type MockaccountCreator struct {
	ctrl     *gomock.Controller
	recorder *MockaccountCreatorMockRecorder
	isgomock struct{}
}

// MockaccountCreatorMockRecorder is the mock recorder for MockaccountCreator.
type MockaccountCreatorMockRecorder struct {
	mock *MockaccountCreator
}

// NewMockaccountCreator creates a new mock instance.
func NewMockaccountCreator(ctrl *gomock.Controller) *MockaccountCreator {
	mock := &MockaccountCreator{ctrl: ctrl}
	mock.recorder = &MockaccountCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccountCreator) EXPECT() *MockaccountCreatorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockaccountCreator) Execute(ctx context.Context, documentNumber string) (*domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, documentNumber)
	ret0, _ := ret[0].(*domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockaccountCreatorMockRecorder) Execute(ctx, documentNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockaccountCreator)(nil).Execute), ctx, documentNumber)
}
