// Code generated by MockGen. DO NOT EDIT.
// Source: transaction.go
//
// Generated by this command:
//
//	mockgen -source=transaction.go -destination=mocks/transaction_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/nubank/pismo-code-assessment/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MocktransactionCreator is a mock of transactionCreator interface.
type MocktransactionCreator struct {
	ctrl     *gomock.Controller
	recorder *MocktransactionCreatorMockRecorder
	isgomock struct{}
}

// MocktransactionCreatorMockRecorder is the mock recorder for MocktransactionCreator.
type MocktransactionCreatorMockRecorder struct {
	mock *MocktransactionCreator
}

// NewMocktransactionCreator creates a new mock instance.
func NewMocktransactionCreator(ctrl *gomock.Controller) *MocktransactionCreator {
	mock := &MocktransactionCreator{ctrl: ctrl}
	mock.recorder = &MocktransactionCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktransactionCreator) EXPECT() *MocktransactionCreatorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MocktransactionCreator) Execute(ctx context.Context, accountID int64, operationTypeID int, amount float64) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, accountID, operationTypeID, amount)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MocktransactionCreatorMockRecorder) Execute(ctx, accountID, operationTypeID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MocktransactionCreator)(nil).Execute), ctx, accountID, operationTypeID, amount)
}
